# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briscola', '0002_auto_20170104_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('edit_comment', 'Can edit the comment'), ('create_comment', 'Can create the comment'))},
        ),
    ]
